const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const addressSchema = mongoose.Schema({
  pincode: {
    type: String,
    required: false,
    trim: true,
    default: "",
    min: 6,
    max: 6,
  },
  city: { type: String, required: false, trim: true, default: "" },
  state: { type: String, required: false, trim: true, default: "" },
  country: { type: String, required: false, trim: true, default: "" },
  address1: { type: String, required: false, trim: true, default: "" },
  address2: { type: String, required: false, trim: true, default: "" },
  landmark: { type: String, required: false, trim: true, default: "" },
  name: { type: String, required: false, trim: true, default: "" },
  email: { type: String, required: false, trim: true, default: "" },
  number: { type: String, required: false, trim: true, default: "" },
});
const UserSchema = new Schema(
  {
    device_token: { type: String, required: false, trim: true, default: "" },
    name: { type: String, required: false, trim: true, default: "" },
    company_name: { type: String, required: false, trim: true, default: "" },
    pincode: { type: String, required: false, trim: true, default: "" },
    city: { type: String, required: false, trim: true, default: "" },
    state: { type: String, required: false, trim: true, default: "" },
    country: { type: String, required: false, trim: true, default: "" },
    address1: { type: String, required: false, trim: true, default: "" },
    address2: { type: String, required: false, trim: true, default: "" },
    landmark: { type: String, required: false, trim: true, default: "" },
    mobile: {
      type: String,
      required: true,
      trim: true,
      unique: true,
      default: "",
    },
    mobileotp: { type: String, required: false, trim: true, default: "" },
    email: { type: String, required: false, trim: true, default: "" },
    permanenet_address: {
      type: String,
      required: false,
      trim: true,
      default: "",
    },
    shipping_address: [
      {
        type: addressSchema,
        required: false,
        default: {
          name: "",
          email: "",
          number: "",
          pincode: "",
          city: "",
          state: "",
          country: "",
          address1: "",
          address2: "",
          landmark: "",
        },
      },
    ],
    role: { type: String, required: false, trim: true, default: "" },
    is_both_address_same: {
      type: Boolean,
      required: false,
      trim: true,
      default: false,
    },
    password: { type: String, required: false, trim: true, default: "" },
    cover_pic: [{ type: String, required: false, trim: true }],
    profile_pic: { type: String, required: false, trim: true, default: "" },
    is_approved: { type: Boolean, required: false, trim: true, default: false },
    is_delete: { type: Boolean, required: false, trim: true, default: false },
    is_email_verified: {
      type: Boolean,
      required: false,
      trim: true,
      default: false,
    },
    is_mobile_verified: {
      type: Boolean,
      required: false,
      trim: true,
      default: false,
    },
    is_token: { type: String, default: "" },
    notificationList: [],
    stripeCustomer: {},
  },
  { timestamps: true, toObject: { virtuals: true }, toJSON: { virtuals: true } }
);
module.exports = mongoose.model("User", UserSchema);
