require('dotenv').config();

module.exports = {
    PORT: process.env.PORT,
    PROXY: process.env.PROXY,
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    MAILTRAP_USER: process.env.MAILTRAP_USER,
    MAILTRAP_PASS: process.env.MAILTRAP_PASS,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    WHATSAPP_INSTANCE_ID: process.env.WHATSAPP_INSTANCE_ID,
    WHATSAPP_ACCES_TOKEN: process.env.WHATSAPP_ACCES_TOKEN,
    GMAIL_USER: process.env.GMAIL_USER,
    GMAIL_PASS: process.env.GMAIL_PASS,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    apiToken: process.env.apiToken,
    S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
    S3_SECRET_KEY: process.env.S3_SECRET_KEY,
    S3_UPLOAD_KEY: process.env.S3_UPLOAD_KEY,
    S3_UPLOAD_SECRET: process.env.S3_UPLOAD_SECRET,
    S3_UPLOAD_BUCKET: process.env.S3_UPLOAD_BUCKET,
    S3_UPLOAD_REGION: process.env.S3_UPLOAD_REGION,
    DTOKEN: process.env.DTOKEN,
    MAKEMYSMS_USER: process.env.MAKEMYSMS_USER,
    MAKEMYSMS_PASS: process.env.MAKEMYSMS_PASS,
    MAKEMYSMS_SENDER: process.env.MAKEMYSMS_SENDER,
    MDSSEND_USER: process.env.MDSSEND_USER,
    MDSSEND_APIKEY: process.env.MDSSEND_APIKEY,
    MDSSEND_SENDERID: process.env.MDSSEND_SENDERID,
    GMAIL_USER_OTP: process.env.GMAIL_USER_OTP,
    GMAIL_PASS_OTP: process.env.GMAIL_PASS_OTP,
    COMPANY_EMAIL: process.env.COMPANY_EMAIL,
    COMPANY_PHONE: process.env.COMPANY_PHONE,
    COMPANY_NAME: process.env.COMPANY_NAME,
    SALT: process.env.SALT
};
